name: Node-js-ci
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
      
      - name: Install Dependencies
        run: npm install
      - name: Install Mocha
        run: npm install mocha --save-dev

      - name: Run test
        run: npm test
