name: Node-js-ci
on:
  push:
    branches:
      - dev
permissions:
  contents: read
  actions: read
  security-events: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
     fail-fast: false
     matrix:
       node-version: [14.x,16.x,18.x,20.x]
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install

      - name: Install Mocha
        run: npm install mocha --save-dev

      - name: Install NYC
        run: npm install nyc --save-dev

      - name: Run test Coverage
        run: npm run coverage

      - name: SonarQube 
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.NODE_SONAR }} 
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=${{ vars.PROJECT_NAME }} 
            -Dsonar.organization=${{ vars.ORG_NAME }} 
            -Dsonar.branch.name=dev 
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        
       # Quality Gate     
      - name: Sonar Quality Gate Check
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.NODE_SONAR }}

      - name: Upload Coverage Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-node-${{ matrix.node-version }}
          path: coverage/
      
      - name: Upload Application Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-app-${{ matrix.node-version }}
          path: nodejs-app-${{ matrix.node-version }}

