name: Node-js-ci
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm install

      - name: Install Mocha
        run: npm install mocha --save-dev

      - name: Run test
        run: npm test

      - name: SonarQube 
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.NODE_SONAR }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=${{ vars.PROJECT_NAME }} 
            -Dsonar.organization=${{ vars.ORG_NAME }} 
            -Dsonar.branch.name=dev 
  

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-app
          path: .

